---
date: "2016-04-27T00:00:00Z"
external_link: ""
image:
  caption: 
  focal_point: Smart
links:
summary: dynamic data visualization
tags:
- GIS
- Urban Planning
title: Data Viz
url_code: ""
url_pdf: ""
url_video: ""
---

```{css, echo=FALSE}
div.sourceCode {
    overflow: hidden;
}
```


```{r include=FALSE, warning=F, message=F}
knitr::opts_chunk$set(comment = NA)
```

```{r, warning=F, message=F, include=F}
library(pacman)
p_load(tidyverse, readxl, lubridate, purrr, janitor, scales, plotly, tmap, leaflet, DT,lubridate,sf,xfun, ggridges, ggmap)
```

```{r message=FALSE, warning=FALSE, echo=F}
continuous<-read_csv("C:/Users/reidh/Documents/R/scratch/validation_traffic_counts/analysis_methodology/continuous.csv") %>%
  mutate(weekday=wday(Date, label=TRUE), month=month(Date, label=TRUE), Day1=as.character(Day))
```

Data is increasingly presented in web-based forums. We utilize popular data visualization libraries such as plotly, leaflet, and ggplot

## Distribution Plots

```{r warning=F, message=F, echo=F, out.width="150%"}
ggplotly(
continuous %>% 
  group_by(Day) %>% 
  summarise(Count=sum(Count, na.rm=T)) %>% 
  ggplot(aes(Count)) +
  geom_histogram(aes(y=..density..),colour="black", fill="white") +
  geom_density(alpha=.2, fill="#FF6666")  +
  theme_minimal() +
  theme(axis.title.x = element_blank(), axis.text.y=element_blank(), axis.title.y=element_blank())
)
```

## Box & Whisker Plots

```{r warning=F, message=F, echo=F, out.width="150%", out.height="100%"}
options(scipen=999)

ggplotly(
continuous %>%
  group_by(Day,month, weekday) %>%
  summarise(Count=sum(Count,na.rm=T)) %>%
ggplot(aes(x = weekday, y = Count, color = weekday)) +
  theme(axis.text.x=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), axis.ticks.x=element_blank()) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(~month) + theme(legend.position="bottom") +
  scale_color_manual(values=c("#08D6DA", "#06378D", "#BE0B05", "#F7A537", "#DEF006", "#35AA27", "#940CD8")), height=800) %>%
  layout(legend = list(orientation = "h", x = 0.0, y = -0.2)) %>%
  style(legendgroup = NULL)
```

## Raw Observations Grouped

```{r, warning=F, message=F, echo=F, out.width="130%"}
ggplotly(
  continuous %>% group_by(Day, station) %>% 
    summarise(Count=sum(Count)) %>% ggplot(aes(Day, Count, group=station, fill=station)) + 
    geom_col()+theme_minimal() + theme(axis.title.x=element_blank(), legend.position = "none", axis.title.y=element_blank()) + scale_x_date() 
  )
```

## Time Series Charts

```{r, warning=F, message=F, echo=F, out.width="130%"}
all_days<- continuous %>% 
  group_by(weekday, Day) %>% 
  summarise(Count=sum(Count, na.rm=T)) %>% 
  ungroup()

ggplotly(
  ggplot(all_days, aes(Day,Count, group=weekday, color=weekday)) + geom_line() + theme_minimal() + theme(axis.title.y = element_blank())) %>%
  layout(legend = list(orientation = "h", x = 0.0, y = -0.3)) 

```

## Stacked Charts

```{r warning=F, message=F, echo=F}
ggplotly(
continuous %>% 
  group_by(Day, month, station) %>%
  summarise(Count=sum(Count,na.rm=T)) %>%
  group_by(month, station) %>%
  summarise(Count=median(Count)) %>% 
  ggplot(aes(month, Count, group=station, fill=station)) + geom_col() + theme_minimal() +
   theme(legend.title = element_blank(), axis.title.x=element_blank(),axis.title.y=element_blank(), axis.text.y=element_blank(),
        axis.text.x=element_text(size=12), legend.position = "none") 
)
```


## Facetted Plots

```{r warning=F, message=F, echo=F, out.width="150%"}
ggplotly(
continuous %>% 
  group_by(wday_wknd, ext_int,Day) %>% 
  summarise(Count=sum(Count, na.rm=T)) %>%
  ggplot(aes(Day,Count)) + geom_line(size=1) +
  facet_grid(wday_wknd ~ ext_int ) +
  theme(legend.position="bottom", legend.title = element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(),
        axis.text.x=element_text(angle=34, hjust=1)) +
  scale_y_continuous(labels=scales::comma)
)
```

## Tile Grids

```{r warning=F, message=F, echo=F, out.width="140%"}
ggplotly(
continuous %>%
  group_by(Day, weekday, month, station, ext_int) %>%
  summarise(Count=sum(Count)) %>%
  mutate(dummy="") %>%
ggplot(aes(dummy,station,  fill = Count)) + 
  geom_tile(colour = "white") + 
  facet_grid(weekday~month) + 
  scale_fill_gradient(low="red", high="green") +
  theme(axis.ticks.x=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), axis.text.y=element_text(size=7), axis.text.x=element_blank()), height = 950)
```


