---
external_link: ""
date: "2017-08-01"
image:
  caption: Photo by Reid Haefer
links:
summary: estimating & forecasting
tags:
- Transportation
- Modeling
title: Data Modeling
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

Harospec specialize in creating complex but transparent and easily understandable models. Activity-based travel models (ABMs) are useful tools for estimating and forecasting transportation conditions by microsimulating the behavior of all parties and individuals that travel within a region. The Tahoe Regional Planning Agency was one of the original adopters of the CT-RAMP framework for ABMs and maintains the model in order to understand both resident and visitor travel in the Tahoe region of California and Nevada. As part of my role as managing the Tahoe model, I created an R-Shiny based tool for daylighting the model using graphs, maps, and explainatory text features. The tool allows the user to view raw data inputs, summary charts, maps, and also provide feedback.


```{r, out.width="180%", echo=FALSE, warning=FALSE, error=FALSE}
knitr::include_url("https://reidhaefer.shinyapps.io/model_dashboard/", height="800px")
```
