---
external_link: ""
date: "2018-06-01"
image:
  caption: 
links:
summary: Vehicle Crashes
tags:
- Animation
- Data Viz
- GIS
title: Animation
url_code: ""
url_pdf: ""
url_video: ""
---

```{r, warning=F, message=F, include=F}
library(pacman)
p_load(tidyverse, readr, readxl, lubridate, purrr, janitor, scales, plotly, tmap, leaflet, DT,lubridate,sf,xfun, ggridges, ggmap,tidycensus, leaflet, geojsonio, sf, tmap, tmaptools, DT, xfun,ceramic, gganimate, geojsonio,  gifski, transformr, ggspatial)
```

Animations are a useful for displaying dynamic changes in data over time and space. We utilize quick and cost-effective animation libraries such as [gganimate](https://github.com/thomasp85/gganimate) to create data visualizations for mapping and other purposes. The example below displays vehicle crashes in the Lake Tahoe rgion over time.

```{r, warning=F, message=F, echo=F, out.width="170%"}
register_google(key = "AIzaSyBBVBD3Y_tifwVFsC0sWq6vlK44RXlM-i8")

crash <- geojson_read("https://opendata.arcgis.com/datasets/8753e4259d7b464ead6a4b5be99f2346_16.geojson", what="sp") %>%
  st_as_sf() %>%
  mutate(date=as.Date(date))

crash1 <- bind_cols(crash, data.frame(st_coordinates(crash)))

a<-ggmap(get_map(location = c(lon = -120.0324, lat =39.0968 ),
                 zoom = 11, scale = 2,"satellite"))

p<-a +
  geom_point(data=crash1, aes(x=X,y=Y),shape = 21, colour = "white", fill = "red", size = 3, stroke = 1 ,show.legend = FALSE) +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), axis.title=element_blank()) +
  transition_time(date) + ease_aes('linear') +
  labs(title = 'Tahoe Vehicle Crashes Over Time: {frame_time}') +
  shadow_mark(alpha=0.2, size=3, colour="white", fill="white")
animate(p, fps=5)
```